### PR TITLE
Improved GeoLocation

### PR DESCRIPTION
**Pull request by d3agle**
Implemented a more reliable geo location service

### CODE REVIEW

**Comment by MaxXor** [comment]
Please add this as a second option and execute it only when the first one fails.

**Comment by d3agle** [comment]
Oh woops, ok I can do that.  Take a look at the refactoring and let me know what you think... This service is much more reliable than the other one and we can extract more information as well.  Is there a reason why https should be used over http?  If the client is on a VPN of some sort without the ability to use https protocol it will fail

**Comment by MaxXor** [comment]
@d3agle Thanks. I don't want to send any unencrypted requests. Who uses a VPN that can't handle https LOL?

**Comment by d3agle** [comment]
That is true lol, I was just testing it over 143vpn and their DE server doesn't support https requests :(  

So do you want me to revert back to using the old service as a primary or would you like the new service to be implemented?  It would be much faster to use the new service because it is very fast, reliable, and we can extract IP information in one call! :D

**Comment by MaxXor** [comment]
Okay, use http and use the new service as the first choice. We keep the old as a fallback.

**Comment by d3agle** [comment]
Ok to use http?  Don't merge just yet, gotta fix one thing

**Comment by MaxXor** [comment]
@d3agle Yes it's ok to use http.

**Comment by d3agle** [comment]
Wonderful, thank you! Is good to go now. :D

**Comment by d3agle** [comment]
Oops forgot null reference checks, sorry LOL one second

**Comment by d3agle** [comment]
Going to send this in one PR so the commits don't look sloppy

**Comment by MaxXor** [comment]
Thanks.

**Pull request closed without merging**
