### PR TITLE
Startup items fix

### PR DESCRIPTION
**Pull request by yankejustin**
Fixes <b><a href="https://github.com/MaxXor/xRAT/issues/256">Issue 256</a></b>.
I have no time to post a better description, so I apologize. I need to clean the method that removes registry key items later. :)

### CODE REVIEW

**Comment by MaxXor** [comment]
Added it. No need to worry about.

**Comment by MaxXor** [comment]
I have to admit, these changes didn't even work after I've fixed them. :(

**Comment by DragonzMaster** [comment]
The problem that startup manger only works on my pc @MaxXor :(

**Comment by MaxXor** [comment]
Use the latest commit.

**Comment by DragonzMaster** [comment]
@MaxXor 
Unfortunately it seems that I still have this problem
xr3

**Comment by yankejustin** [comment]
Start the client in debug and see the exception that is thrown please.

**Comment by DragonzMaster** [comment]
It is working good on my pc but when I send it to someone it doesn't work as shown in the picture
So do you mean that I have to send debug client to instead of release ??
@yankejustin

**Comment by MaxXor** [comment]
no, he doesn't mean this. Please update your clients to the latest version please. :) And it will show you the error, please tell me this.

**Comment by MaxXor** [comment]
Please write in your https://github.com/MaxXor/xRAT/issues/256.

**Pull request merged**
