### PR TITLE
Form disposal on client disconnection

### PR DESCRIPTION
**Pull request by d3agle**
Added disposal method to dispose of all userstate forms for client upon
disconnection of the client from the server

### CODE REVIEW

**Comment by d3agle** [comment]
Please close, will push mergable version

**Comment by MaxXor** [comment]
Why, your pull requests are fine?

**Comment by d3agle** [comment]
I'm not sure if you are able to merge them, I'm not very familiar with github.  Also, I jumped the gun with the two bugfix commits and they are practically useless.  I will post an bug/issue topic regarding the issue with the bugs.   The code for this specific commit could however be of use

**Comment by MaxXor** [comment]
The other two are fine too. :) I'll add them.

**Pull request merged**
