### PR TITLE
New Keylogger

### PR DESCRIPTION
**Pull request by yankejustin**
Hi!
Here is the re-written keylogger!

@MaxXor Please make a separate branch for this because there are a few more things that should be either fixed, added, or modified with this keylogger before it should be added to the main branch. Please see <b>Upcoming</b> and <b>To-Do</b>.

<b>Features</b>
- Flexible and dynamic behavior
- Easy to modify
- Encapsulation
- Supports many more keys (again, extremely easy to add more)
- Documentation!
- Uses Virtual Keys <i>then</i> calls ToUnicodeEx for better localization.

<b>Upcoming (before merging)</b>
- Attempt to use keys that are not supported in our enum list by attempting to use FromKeys.
- Be sure https://github.com/MaxXor/xRAT/issues/95 is fixed
- Be sure https://github.com/MaxXor/xRAT/issues/98 is fixed
- Be sure https://github.com/MaxXor/xRAT/issues/99 is functional
- Add support for more keylogger keys
- Correctly detect the state of caps lock, scroll lock, and num lock

<b>To-Do</b>
- Improve code and optimize (much later... probably after upcoming is done and after adding to the master branch)
- More testing on the output... A few known unreliable things, such as: pressing 'alt' key or 'ctrl' key will print the correct key (such as '[CTRL]' for the correct key, but will then also print '[L_CTRL]' because it was the control key from the left...)
- Improvements to the interface, including things like being able to easily access or modify log files, colorizing, etc. https://github.com/MaxXor/xRAT/issues/90
- Add the ability to dynamically re-assign the output, as specified in https://github.com/MaxXor/xRAT/issues/111
- Add a maximum size cap. for log files and add folders for each day instead of files because they get long. Also handle multiple or repetitive keys in a more elegant way, as specified in https://github.com/MaxXor/xRAT/issues/119
- Eventually encode the formatted output of the keylogger so it is not vulnerable to Cross-Site Scripting (XSS)

### CODE REVIEW

**Comment by DragonzMaster** [comment]
I see that you have a lot of work to do
good luck bro :D

**Comment by yankejustin** [comment]
Hehe... Yeah, it is quite a lot of work, but might as implement a new and big feature correctly to make it easier for future changes and modifications! :)
A big reason for asking for a separate branch from my last commit is because it is in a <i>functional</i> state. Not the desired state, but it works. Making a branch from my current progress means that many others will be able to take some of the work and contribute to this new major change to a big part of what makes up a wholesome Remote Administration Tool. :100:

**Comment by MaxXor** [comment]
Created the new branch `dev` for this.

**Comment by d3agle** [comment]
Good work @yankejustin, I'm making some changes to this to get the toggle/down keys to work correctly.  One thing I've noticed is that keys are sometimes logged multiple times just pressing the key once, maybe you could have some insight on why this is happening

**Comment by yankejustin** [comment]
@d3agle Thank you! :)
Yeah I will have to toy with the output tonight. The big priority is making sure that the special keys are being captured, and that the toggle state of the keys is being correctly detected.
The reason that the keys are logged multiple times is because the value of the keys that have multiple values (ctrl = l_ctrl | r_ctrl) so I think I am just neglecting to pull only a single flag out of the input we are given...

**Comment by yankejustin** [comment]
Another priority is the interface, but we (of course) need the output to be accurate and correctly formatted. :)

**Comment by yankejustin** [comment]
@MaxXor Can my fork be deleted without affecting your branch? I should have used a different branch instead of my fork's master branch to work on the keylogger... :P

**Comment by MaxXor** [comment]
@yankejustin yes. :) it's safe to delete.

**Comment by yankejustin** [comment]
Okay, good. Thank you!

**Comment by d3agle** [comment]
I hate to say this, but I don't think that this key logger is going to work, as far as accuracy and efficiency.  I've done a lot of research on GetAsyncKeystate and it doesn't appear that this method contains enough information to have accurate control on what we are trying to accomplish.  Initially, I wanted to avoid global keyboard hooks when I was looking into this method, but considering there would be a lot more control over the accuracy and efficiency of recording keystrokes (filtering system messages), I think that using a keyboard hook might be a more viable option.

**Comment by yankejustin** [comment]
Yeah, I agree. Throughout my extensive research on all hookless methods to do this, I have consistently seen horribly poor documentation by Microsoft, inconsistent behavior with the methods provided, and just simply incorrect behavior that seems to be experienced by others as well. It feels that, even if done correctly, <b>this is going to end up being one hacky fix after another</b> in order to implement a functioning and <i>accurate</i> keylogger.

**Comment by yankejustin** [comment]
@MaxXor We need your input on this. I have been doing more research in my free-time (about to work on some open issues soon), and I have also come to the conclusion that using a keyboard hook would be far better of a solution due to the unpredictable and poorly-understood <i>GetAsyncKeystate</i>

**Comment by d3agle** [comment]
I have implemented a low level hook, however the callback delegate is not firing.  At first, the client would crash without adding the Keylogger namespace in the Renamer class for the server, but I can't figure out why the callback method is not executing.  Any ideas why?

**Comment by MaxXor** [comment]
I think we should try out using a keyboard hook. :) Let's see how this is working.

**Comment by yankejustin** [comment]
I am going to close this pull request because most of it is in the "dev" branch. I will be committing some new changes so we are using a keyboard hook instead of <i>GetAsyncKeystate</i>.

**Comment by MaxXor** [comment]
Alright!

**Pull request closed without merging**
