### PR TITLE
Some form fixes

### PR DESCRIPTION
**Pull request by d3agle**

### CODE REVIEW

**Comment by MaxXor** [comment]
The MainForm fix is invalid, both do the same. Can you please create a new pull request with the Threaded Upload and execute?

**Comment by d3agle** [comment]
How would I go about this?  I'm not sure how you mean.  Sorry, I'm not very good with github.

**Comment by MaxXor** [comment]
The fastest way I could think of is deleting your fork and recreating it again with the new changes.

**Comment by d3agle** [comment]
Sure, one sec

**Pull request closed without merging**
