### PR TITLE
Remote shell fixes

### PR DESCRIPTION
**Pull request by yankejustin**
<h1>Fixes</h1>
1. Remote Shell Form is now set to double-buffered.
    - Fixes an issue with the Remote Shell Form flickering.
2. Handling "exit" commands.
    - No longer directly sends an "exit" command to the client because <code>this.Close()</code> is called. In such context, the Remote Shell Form is closed. The Remote Shell Form is subscribed to an event that will send an "exit" command to the client when the Remote Shell Form is closing. There is no need to send two "exit" commands.
3. The output TextBox for the Remote Shell Form is now a <code>RichTextBox</code>.
    - Allows correct colorization of appended text.

<h1>Changes</h1>
1. Handling "exit" commands.
    - Changed how it is handled: correctly parsed from a command and handled correctly.
2. <code>Dispose(bool)</code>.
    - <code>Dispose(bool)</code> should not suppress finalization. Finalization suppression should be determined by <code>Dispose()</code>.
    - Now disposes of the new <code>ManualResetEvent</code> objects.

<h1>Additions</h1>
1. Added a property to RemoteShellCommandResponse (IsError).
    - This new property denotes how it should be handled: it the RemoteShellCommand responded with an error (IsError = true), we should print it differently (red).
2. Added an interface (<code>IRemoteShell</code>) for the RemoteShellForm.
    - Provides methods to use specifically for printing regular messages or errors.
    - More readable.
    - By routing all of the output messages and error messages to the same spot, changing or extending on these features are significantly easier.
3. Multi-threaded output chaining.
    - Created new thread that handles the output of errors in the shell.
    - Added a new method that queues up the threads used to chain the two different outputs together.

### CODE REVIEW

**Comment by yankejustin** [comment]
@d3agle Would you mind helping me test this new one out? I just wrote it today so it may have something I didn't catch yet.

**Comment by yankejustin** [comment]
<h1>Fixes the following issues:</h1>
- <b><a href="https://github.com/MaxXor/xRAT/issues/223">Issue 223</a></b>
- <b><a href="https://github.com/MaxXor/xRAT/issues/216">Issue 216</a></b>

**Comment by d3agle** [comment]
Sure thing.  :)

**Comment by d3agle** [comment]
Everything looks good so far from what I can tell.  One little thing I noticed was, say I have a directory with many dirs/files inside and i run the dir command.  While it's returning the output to the server, it's also taking input from the server.  Say I spam `pause` while its sending the server the output of executing `dir`.  It will look like this: http://i.gyazo.com/4b5c3638f195449e46ee8ea4a26f30a7.mp4

**Comment by d3agle** [comment]
I'm assuming that the command had already completed and the output is still being sent, it mixes the two together

**Comment by yankejustin** [comment]
I couldn't help but notice the <b>Riot Games</b> part... I only play ARAM these days, but I usually spend free-time programming and learning! ;)
Also, I think this issue is, as you stated, issues with packet order... Hmmm...

**Comment by yankejustin** [comment]
@d3agle Please try to remove the <code>Thread.Sleep(200);</code> for both redirecting methods. It seems as though that is butchering the output by stopping the message chain too long when handling more data. I am not sure why that was in the original logic anyways... Probably to ensure ordered packets I would assume...

**Comment by d3agle** [comment]
Haha :D I had installed League of Legends a while back, and played for probably 10 minutes before losing interest. Just wasn't a game I could get into.  I will remove that call and see if it fixes the issue.  Everything other than that looks good,  I think I might have a hard time inputting text that might not tolerate well on the client, but I'll see if I can break it.

**Comment by d3agle** [comment]
Now the output is extremely fast, which is nice.  This is what it looks like: http://i.gyazo.com/eb1cbe540425c5f4503d4a0b34684e61.mp4

It appears a little weird, but I think its because of gyazo.  looks fine on my screen. 

I'm assuming the end goal would be to have a shell that operates similar to what opening a command prompt would display, so theres a bit more work as far as behaviors.  For example, in that .gif, executing pause on a new line won't display the output until another command is executed

**Comment by MaxXor** [comment]
This does not correctly kill the spawned process `cmd.exe` please fix this!!

**Comment by MaxXor** [comment]
Done.

**Pull request merged**
