### PR TITLE
UPnP ensure port map

### PR DESCRIPTION
**Pull request by d3agle**
ref #289 

In my case, one of my devices didn't map the port until the second iteration, so we just probe the router with multiple requests to make sure that it is ready to process mapping the port.

### CODE REVIEW

**Comment by MaxXor** [comment]
Very strange that it doesn't work on the first try. :s

**Comment by d3agle** [comment]
I know :(  I'm not sure whether its a device issue or library issue...   This commit would just send multiple requests to the router, and wouldn't mess up any other object or functionality that was originally implemented.  I tested it on both devices multiple times without any issues :D

**Comment by d3agle** [comment]
I believe this is the best solution, until the underlying cause is found...  I will have to sniff my network to see what is happening whether it is a device issue or a packet issue from the code in the library.  I'm thinking its probably just the device though!

**Comment by MaxXor** [comment]
Yes, you should check with a packet sniffer the response from the router after your first try fails, maybe we find the reason.

**Comment by d3agle** [comment]
Ok, so the first attempt is getting a 400 error Bad request malformed packet, and the second attempt is getting the correct response but is still considered a malformed packet.

**Pull request merged**
