### PR TITLE
Started adding unit tests into the Client. 

### PR DESCRIPTION
**Pull request by tidusjar**
Hello,

I have started to add some unit tests into the Client. I will proceed with this and eventually start adding some to the Server!

This is using NUnit 3 and Autofixture.

I just thought it would be very useful to have some of these components wrapped around in Unit tests so we don't break anything.

(Note: if I have done the process incorrect apologies! It's my first contribution).

### CODE REVIEW

**Comment by tidusjar** [comment]
Unit testing, making sure the components are functioning correctly so if anyone makes a change, we can then see if it breaks the system without having to manually test each component.

**Comment by tidusjar** [comment]
Can we please add into the AppVeyor.yml ? 
http://www.appveyor.com/blog/2014/03/18/about-nuget-package-restore

This will then allow my branch to build :(

before_build:
  - nuget restore

**Comment by DragonzMaster** [comment]
i am really ashamed to ask this but what is it used for ?

**Comment by tidusjar** [comment]
DragonzMaster, this is for unit testing http://en.wikipedia.org/wiki/Unit_testing . I am working on getting the references and Nuget packages working right now so the Build passes. Checkout my branch and run the tests and you will see what they do. :)

**Comment by bitterypaul** [comment]
thanks for the unit test contribution. btw check out all open issues and please contribute more. thanks

**Comment by tidusjar** [comment]
BitteryPaul, I want to contribute more so I will take a look after I get this build working.

**Comment by bitterypaul** [comment]
wonderful. thecbuild is successful. great work @tidusjar

**Comment by tidusjar** [comment]
Thanks. It was a pain getting Nuget packages to resolve when we have none already! All the work is now done for Nuget!

**Comment by yankejustin** [comment]
It is funny but I was just thinking about this. This is especially necessary for the keylogger and file transfering to ensure the data is being transferred correctly! :)

**Comment by yankejustin** [comment]
@MaxXor This is very important for these data-critical tasks! This makes life easy. :100:

**Comment by tidusjar** [comment]
@yankejustin I plan adding more tests into the solution! It makes things 10000x easier regarding maintainability and reducing bugs

**Comment by MaxXor** [comment]
Hey,
can you add your unit tests to the following unit testing project I've created? Thanks!

**Comment by tidusjar** [comment]
@MaxXor Just wondering why you are not using NUnit? It's a lot more flexible than MSTest. Any why are we not using AutoFixture? The main benefit of AF is that we can quickly mock up populated classes with 1 line.

**Comment by MaxXor** [comment]
At the moment I don't see a need for this, the Client supports some Helper methods which are useful. I also want to keep the dependencies as low as possible.

**Comment by tidusjar** [comment]
@MaxXor Ok no problem. I'm just saying there are a lot of advantages. Should I be doing this in the Master or Dev branch?

**Comment by MaxXor** [comment]
Master please. :)

**Comment by tidusjar** [comment]
Can you also create a project for the Server? I'll start adding some to that too :)

**Pull request closed without merging**
