### PR TITLE
Fixed ProtoWriter's implementation of IDisposable

### PR DESCRIPTION
**Pull request by yankejustin**
Correctly implemented IDisposable on the client's and server's ProtoWriter. This will cause its behavior to be more reliable.
Notable:
1) Original implementation did not suppress finalization (hitting performance a bit).
2) Original implementation specified that it did not want to dispose of the underlying Stream for the ProtoWriter in the comments, but removed the reference to the underlying Stream by setting the Stream to null, causing a memory leak and losing control of the underlying Stream.

### CODE REVIEW

**Comment by MaxXor** [comment]
The ProtoBuf files are not equivalent, please fix this. Better you create a new fork with the latest changes, so you do not have to include this big commit from updating your fork.

**Comment by yankejustin** [comment]
Thank you for your suggestion.
I apologize for not understanding, but is there something I am misunderstanding that is from the changes included?

**Comment by MaxXor** [comment]
All changes you do to the clients protobuf classes you also have to do to the servers protobuf classes to fix it on both sides. For example this: https://github.com/yankejustin/xRAT/commit/be233599dbff9e279bd168cd404e2c20cd99c23d

Also this changed line is just on one side: https://github.com/yankejustin/xRAT/commit/9a10e2f99293dcfa9bf807e32e82d760d2c9aae9#diff-e3f0b1e49796775cc58453272a15332bR545

**Comment by yankejustin** [comment]
For the first example, I had reflected the changes in the third commit. I have now fixed the other examples and they now reflect.

**Pull request closed without merging**
