### PR TITLE
dead-key fix

### PR DESCRIPTION
**Pull request by d3agle**
Fixed case of pressing dead-key to accent characters followed by Shift +
character to present an uppercase character

### CODE REVIEW

**Comment by d3agle** [comment]
@MaxXor , if you see this, please don't merge the pull request just yet. There is still work to do with the case of 2 characters in the buffer (pressing ^ key twice will return ^^) but only displays one of the characters

**Comment by d3agle** [comment]
@MaxXor , this can be merged now!

**Comment by DragonzMaster** [comment]
is everything works good ? @d3agle

**Comment by d3agle** [comment]
@DragonzMaster , yes as far as accenting characters.  The only thing that we need to do is re-design how modifiers are set/checked so we can use, Alt Gr for example, which is equivalent to pressing Control + Alt to display special characters if your keyboard supports this.  We need to devise a strategy other than storing keys in lists.  I think I will start working on this now and see what I can come  up with

**Pull request merged**
