### PR TITLE
Improvements to new content (Keylogger)

### PR DESCRIPTION
**Pull request by yankejustin**
Improved the code in the new Keylogger. Formatted some code to make it consistent with the rest, and optimizations.

### CODE REVIEW

**Comment by yankejustin** [comment]
Oh. Intellisense did not provide that for me when I initially wrote it. That would most likely be faster than converting it to a string and checking that way.

**Comment by yankejustin** [comment]
Would you like me to change that line? I placed that commit that adds the not (!) just to fix the issue before improving it for documentation.

**Comment by MaxXor** [comment]
Yes, please do that change. :)

**Comment by yankejustin** [comment]
:)

**Pull request merged**
