### PR TITLE
Added the ability to upload an execute a batch file.

### PR DESCRIPTION
**Pull request by tidusjar**
Feature for #244

### CODE REVIEW

**Comment by werkamsus** [comment]
Does hidden execution work on them too? If not you might want to add that c:

**Comment by yankejustin** [comment]
This PR, from the title, seems to only be for support of uploading it, not executing it.
I'm actually not quite sure if we can execute executable files hidden already.

**Comment by yankejustin** [comment]
As a note to clarify my comment above, I would just like to say that nothing really has to be done about the execution of the file. It should already be functioning as well as the execution feature of a normal batch file.

**Comment by tidusjar** [comment]
@werkamsus yes it already had the functionality for hidden files. I just built on top of that. 

@Yankejustin good suggestions. Could you expand on point 2 & 3? I had a look how uploading and executing an exe worked and it's just using simply starting a process. This will also work with batch files and the original request is to upload and run .bat files. This archives that. I could have wrote a lot more code and changed things but I decided against it since what was there works, so I just expanded upon it.

**Comment by yankejustin** [comment]
@tidusjar Are you asking about my 2nd and 3rd points from the first comment or the 2nd and 3rd comments? :)
The second and third comments were responses to werkamsus. I was just stating that the existing code for starting the process works pretty good and that this pull request does exactly how it is titled.
In the original comment, the comment I made is actually linked to the line of code I was referring to. It is just a suggestion to improve the code before it is merged with the base repository. :hankey:

**Comment by tidusjar** [comment]
Ah ok that makes sense!
Regarding 
2. Perhaps we should make sure there are two objects in the Block array before indexing the array for positions 0 and 1.
3. Why check command.CurrentBlock == 0 twice?

On your second point do you mean check that there are atleast [0] and [1] before checking, then no exceptions are thrown? Good idea.

3. It's basically two condition checks, in both conditions it needs to be 0. I could move that check above and then short circuit it to save some time but I didn't think it was worth it. But I can change that now.

**Comment by yankejustin** [comment]
Sometimes it is dangerous to assume we can call <code>comand.Block[0]</code> because we can not always be certain the client sent a packet that was correctly-formed. We should check <code>if (command.Block.Count >= 2</code> before indexing it so we know we can't get an <code>IndexOutOfRangeException</code>.
Also, the condition actually goes like this:
1. Check if the <code>CurrentBlock</code> equals 0.
2. Index the array (<code>Block</code>) at position <code>0</code> and position <code>1</code>.
3. Check if the <code>CurrentBlock</code> equals 0.
4. Index the array (<code>Block</code>) at position <code>0</code> and position <code>1</code>.

I was suggesting removing the unnecessary 3rd part as mentioned right above. It has no need to check the <code>CurrentBlock</code> twice.

**Comment by yankejustin** [comment]
Perhaps you meant to include <code>||</code> in the conditional.

**Comment by MaxXor** [comment]
Anyways guys, I've fixed the changes and merged it.

**Comment by tidusjar** [comment]
Sorry I made changes before i seen these. Thanks for the comments.

**Comment by yankejustin** [comment]
Good. :)
Thank you for the contribution.

**Pull request merged**
