### PR TITLE
#220 fix

### PR DESCRIPTION
**Pull request by d3agle**
we are calling to remove the client from the list twice in this class.

Once in the OnClientState method, and once when stopping the listen server.  I'm not sure we need to call Disconnect in the OnClientState method but this I will leave this fix up for now

### CODE REVIEW

**Comment by d3agle** [comment]
https://github.com/d3agle/xRAT/blob/33dfceeb80dc6d1db552dba2bc28c89e05c931a1/Server/Core/Server.cs#L37

and 


https://github.com/d3agle/xRAT/blob/33dfceeb80dc6d1db552dba2bc28c89e05c931a1/Server/Core/Server.cs#L37

**Comment by d3agle** [comment]
These two methods do the same thing.  Just need to determine which one should be calling these

**Comment by d3agle** [comment]
http://gyazo.com/105e000532ebec51031f3f4092c04423 after fix :)

**Comment by yankejustin** [comment]
@d3agle Seems like your comment above (with the two links) are to the exact same line. ;)
Perhaps an error.
Otherwise, nice catch!

**Comment by d3agle** [comment]
aha! thanks for catching that!

**Comment by d3agle** [comment]
The 'edit' commit has the complete fix, just removed some lines

https://github.com/d3agle/xRAT/commit/50741e810452300dc0239ef4b2d33fddb8901d9b

**Pull request closed without merging**
